version: '3'
services:
  flaskapp:
    build: ./Flask
    image: myflask:latest
    volumes:
      - ./Flask:/app
    ports:
      - "5000:5000"
    networks:
      - my-network
  nginx:
    build: ./Web_Server
    image: mynginx:latest
    ports:
      - "80:80"
    depends_on:
      - flaskapp
    networks:
     - my-network
  mongo:
    build: ./movie_db
    image: mymongo:latest
    ports:
      - "27017:27017"
    networks:
     - my-network

networks:
  my-network:
    driver: bridge